// bartime_ofi reference.
// Runtime SQL is generated by:
// core.ddb_intraday_queries.discovery_v1_factor_script(
//     "bartime_ofi", startDate, endDate
// )

startDate = 2024.05.01
endDate = 2024.05.31
btFilter = [09:59:00, 10:29:00, 11:29:00, 13:29:00, 14:29:00]

t = loadTable('dfs://QV_Trade_to_MinuteBar', 'Stock_one_minute')
bars0 = select Symbol, Date, second(Bartime) as Bartime,
    iif(isValid(Active_buy_amount) and Active_buy_amount > 0,
        Active_buy_amount, 0.0) as buy_amt,
    iif(isValid(Active_sell_amount) and Active_sell_amount > 0,
        Active_sell_amount, 0.0) as sell_amt
    from t
    where Date between startDate : endDate
      and ((second(Bartime) >= 09:30:00 and second(Bartime) <= 11:30:00)
        or (second(Bartime) >= 13:00:00 and second(Bartime) <= 15:00:00))

bars = select Symbol, Date, Bartime, buy_amt, sell_amt,
    iif(buy_amt + sell_amt > 0,
        (buy_amt - sell_amt) \ (buy_amt + sell_amt), NULL) as bar_ofi
    from bars0
    context by Symbol, Date csort Bartime

result = select Symbol, concatDateTime(Date, Bartime) as bartime,
    bar_ofi as value
    from bars
    where Bartime in btFilter and isValid(bar_ofi)

select Symbol, bartime, value from result
